ALTER TABLE public.criteria_assessment RENAME TO criterion_assessment;

ALTER INDEX idx_criteria_assessment_patient_record_id RENAME TO idx_criterion_assessment_patient_record_id;
ALTER INDEX idx_criteria_assessment_organization_id RENAME TO idx_criterion_assessment_organization_id;

ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_pkey TO criterion_assessment_pkey;
ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_unique TO criterion_assessment_unique;
ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_site_valid TO criterion_assessment_site_valid;
ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_state_valid TO criterion_assessment_state_valid;
ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_side_valid TO criterion_assessment_side_valid;
ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_region_valid TO criterion_assessment_region_valid;
ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_patient_record_id_fkey TO criterion_assessment_patient_record_id_fkey;
ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_organization_id_fkey TO criterion_assessment_organization_id_fkey;
ALTER TABLE public.criterion_assessment RENAME CONSTRAINT criteria_assessment_assessed_by_fkey TO criterion_assessment_assessed_by_fkey;
