/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqRouteImport } from './routes/sq'
import { Route as IndexRouteImport } from './routes/index'

const SqRoute = SqRouteImport.update({
  id: '/sq',
  path: '/sq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sq': typeof SqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sq': typeof SqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sq': typeof SqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sq'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sq'
  id: '__root__' | '/' | '/sq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SqRoute: typeof SqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sq': {
      id: '/sq'
      path: '/sq'
      fullPath: '/sq'
      preLoaderRoute: typeof SqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SqRoute: SqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
