/**
 * JFLS-8 module exports
 */

export {
  JFLS8_QUESTIONS,
  JFLS8_QUESTION_ORDER,
  JFLS8_METADATA,
  JFLS8_INSTRUCTIONS,
  JFLS8_TOTAL_QUESTIONS,
  JFLS8_QUESTIONNAIRE,
  JFLS8_QUESTION_LABELS,
} from "./questions";

export {
  JFLS8_SCALE_OPTIONS,
  JFLS8_SCALE_LABELS,
  JFLS8_OPTION_LABELS,
} from "./options";
