-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."patient_record" add column "last_viewed_at" timestamp with time zone
--  null;
